sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t ShobithNandakumar/Docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ShobithNandakumar/Docker-react npm run test